version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - backend_doan_mongo-db:/data/db
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - backend_doan_redis-db:/data
volumes:
  backend_doan_mongo-db:
    external: true
  backend_doan_redis-db:
    external: true